// export const BASEURL = `${process.env.API_BASE_URL}/dict/api`;
// export const BASEURL = `https://flashionary.ir/dict/api`;
export const BASE_URL = `http://localhost:3001/api/admin`;
export const BASEURL = `http://localhost:3001/api/admin`;
// export const BASEURL = `http://5.75.174.199:3001/api`;
export const BASE_BACKEND_URL = `http://localhost:3001/api/images`
// export const BASEURL = `https://api2.fooladhadad.com/api/admin`;
// export const BASE_URL = `https://api2.fooladhadad.com/api/admin`;
// export const BASE_BACKEND_URL = `https://api2.fooladhadad.com/api/images`;
